# Generated by Django 3.2.6 on 2021-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, verbose_name='login')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
                ('password', models.CharField(max_length=32, verbose_name='Comand1')),
                ('status', models.IntegerField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
