# Generated by Django 3.2.6 on 2021-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0004_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('port', models.CharField(max_length=16, verbose_name='PORT')),
                ('status', models.IntegerField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
            },
        ),
    ]
